//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStandardFramework_POC.Data_Layer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyDatabaseEntities : DbContext
    {
        public MyDatabaseEntities()
            : base("name=MyDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<School> Schools { get; set; }
    
        public virtual ObjectResult<GetMostPopularJob_Result> GetMostPopularJob()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMostPopularJob_Result>("GetMostPopularJob");
        }
    
        public virtual ObjectResult<GetPersonsByJobTitle_Result> GetPersonsByJobTitle(string jobTitleParam)
        {
            var jobTitleParamParameter = jobTitleParam != null ?
                new ObjectParameter("jobTitleParam", jobTitleParam) :
                new ObjectParameter("jobTitleParam", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPersonsByJobTitle_Result>("GetPersonsByJobTitle", jobTitleParamParameter);
        }
    
        public virtual ObjectResult<GetSchoolNames_Result> GetSchoolNames()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSchoolNames_Result>("GetSchoolNames");
        }
    }
}
